services:
  api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    depends_on:
      - mlflow
    volumes:
      - ./:/app

  streamlit:
    build: .
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false
    ports:
      - '8501:8501'
    depends_on:
      - api
    volumes:
      - ./:/app

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: mlflow server --host 0.0.0.0 --port 5000 --allowed-hosts "*" --backend-store-uri sqlite:///mlflow.db --default-artifact-root /app/mlruns
    ports:
      - '5000:5000'
    volumes:
      - ./mlruns:/app/mlruns
